#!/bin/sh

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

LOWER_WARNING_LEVEL=30
UPPER_WARNING_LEVEL=70
BATTERY_DISCHARGING=`acpi -b | grep -v "0%" | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -v "0%" | grep -P -o '[0-9]+(?=%)'`

if [[ $BATTERY_LEVEL -ge $UPPER_WARNING_LEVEL ]] && [ $BATTERY_DISCHARGING -eq 0 ]; then
    dunstify "Battery High Charge Warning." "Battery is at ${BATTERY_LEVEL}%.\nConsider unplugging charger." -u low -i ~/.config/dunst/highbattery.png -r 9991

elif [[ $BATTERY_LEVEL -le $LOWER_WARNING_LEVEL ]] && [ $BATTERY_DISCHARGING -eq 1 ]; then
    dunstify "LOW BATTERY." "${BATTERY_LEVEL}% of battery remaining." -u critical -i ~/.config/dunst/lowbattery.png -r 9991
fi
