#!/bin/bash
# DESCRIPTION: Sends notification when Battery charge depletes below 30% and when battery charges beyond 70%

# Uses acpi -b to get battery info
# Uses Dunst to send notification

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

LOWER_WARNING_LEVEL=30
UPPER_WARNING_LEVEL=70
BATTERY_DISCHARGING=`acpi -b | grep -v "0%" | grep -c "Discharging"`
BATTERY_LEVEL=`acpi -b | grep -v "0%" | grep -P -o '[0-9]+(?=%)'`

[[ $BATTERY_LEVEL -ge $UPPER_WARNING_LEVEL ]] && [ $BATTERY_DISCHARGING -eq 0 ] &&
    dunstify "Battery High Charge Warning." "Battery is at ${BATTERY_LEVEL}%.\nConsider unplugging charger." -u low -i ~/.config/dunst/highbattery.png -r 9991
[[ $BATTERY_LEVEL -le $LOWER_WARNING_LEVEL ]] && [ $BATTERY_DISCHARGING -eq 1 ] &&
    dunstify "LOW BATTERY." "${BATTERY_LEVEL}% of battery remaining." -u critical -i ~/.config/dunst/lowbattery.png -r 9991
